name: Trigger auto deployment for dataservice-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/dataservice-dev-AutoDeployTrigger-90688d93-447f-42a4-9887-40d29482672a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DATASERVICEDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DATASERVICEDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DATASERVICEDEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: valorxacrdev.azurecr.io
          registryUsername: ${{ secrets.DATASERVICEDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DATASERVICEDEV_REGISTRY_PASSWORD }}
          containerAppName: dataservice-dev
          resourceGroup: rg-valorx-dev
          imageToBuild: valorxacrdev.azurecr.io/dataservice-dev:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


