name: Trigger auto deployment for email-service-dev

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/email-service-dev-AutoDeployTrigger-18e15479-5a6f-425e-979f-cd60b4184295.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.EMAILSERVICEDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EMAILSERVICEDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EMAILSERVICEDEV_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: valorxacrdev.azurecr.io
          registryUsername: ${{ secrets.EMAILSERVICEDEV_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EMAILSERVICEDEV_REGISTRY_PASSWORD }}
          containerAppName: email-service-dev
          resourceGroup: rg-valorx-dev
          imageToBuild: valorxacrdev.azurecr.io/email-service-dev:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


